<html>
	<head>
		<meta charset="utf-8">
		<title> Smart Home</title>
		<link rel="stylesheet" href="css/style-reg-auth.css">
        <link rel="stylesheet" href="css/style.css">

		<!-- Google Fonts Autogenerated embed code -->
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Anonymous+Pro:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

		<!-- Google Charts -->
		<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
	</head>
	<body>
	<?php session_start();?>
    <header>
		<!-- Context -->
		<?php 
			if(isset($_SESSION["now_user_login"]) AND !empty($_SESSION["now_user_login"]))
       			$titleHead = "User: ".$_SESSION["now_user_login"];
			else 
				$titleHead = "<span style='font-family:Impact;'>SmartHome</span>";
			echo "<div class='status'><p>$titleHead</p></div>";
		?>
		<!-- Site title -->
		<div class="site-title">
			<h1> Умный Дом  </h1>
		</div>
		<!-- Logo -->
		<div class="logo">
			<img src="https://cdn1.ozone.ru/s3/multimedia-9/6616033677.jpg" alt="чай улун">
		</div>
	</header>
	<?php 
	
	include "includes/database.php";
	if(!isset($_SESSION['now_user_login']) || empty($_SESSION['now_user_login'])) { ?>
		<div class="error-message"><a href="<?php echo "/smarthome/index.php"; ?>">Войдите</a> или <a href="/smarthome/reg.php">зарегистрируйтесь</a></div>
		<?php die();		
	} else if($_SESSION['now_user_id_access'] > 1) {?>
		<div class="error-message">Ваш аккаунт ещё ожидает одобрения администратором. <a href="<?php echo "/smarthome/index.php?exit=1"; ?>">Завершите сессию</a> чтобы войти в другой аккаунт.</div>
		<?php die();
	}
?>	
	